Vagrant.configure("2") do |config|
  # set os
  config.vm.box = "centos/7"
  config.vbguest.auto_update = false

  # config ssh
  config.ssh.insert_key = false

  # global setup VM
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  # setup server
  config.vm.define "sbelondrS" do |control|
    control.vm.hostname = "sbelondrS"
	control.vm.network "private_network", ip: "192.168.42.110"

	control.vm.provider "virtualbox" do |v|
	  v.name = "sbelondrS"
    end

	config.vm.provision "file", source: "./scripts/create_volume_map.sh", destination: "/home/vagrant/create_volume_map.sh"
	config.vm.provision "file", source: "./confs/kube-logo.svg", destination: "/home/vagrant/kube-logo.svg"
	config.vm.provision "file", source: "./confs/app1", destination: "/home/vagrant/app1"
	config.vm.provision "file", source: "./confs/app2", destination: "/home/vagrant/app2"
	config.vm.provision "file", source: "./confs/app3", destination: "/home/vagrant/app3"
	config.vm.provision "file", source: "./scripts/scriptS.sh", destination: "/tmp/scriptS.sh"

    # install and config k3s
    control.vm.provision "shell", inline: <<-SHELL
	  bash /tmp/scriptS.sh
    SHELL
  end

end
