Vagrant.configure("2") do |config|
  # set os
  config.vm.box = "centos/7"
  config.vbguest.auto_update = false

  # config ssh
  config.ssh.insert_key = false

  # global setup VM
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  # setup server
  config.vm.define "sbelondrS" do |control|
    control.vm.hostname = "sbelondrS"
	control.vm.network "private_network", ip: "192.168.42.110"

	control.vm.provider "virtualbox" do |v|
	  v.name = "sbelondrS"
    end

	config.vm.provision "file", source: "./scripts/scriptS.sh", destination: "/tmp/scriptS.sh"
    # install and config k3s
    control.vm.provision "shell", inline: <<-SHELL
	  bash /tmp/scriptS.sh
    SHELL
  end

  # setup agent
  config.vm.define "sbelondrSW" do |control|
    control.vm.hostname = "sbelondrSW"
 	control.vm.network "private_network", ip: "192.168.42.111"
 
	# set name for the VM
 	control.vm.provider "virtualbox" do |v|
 	  v.name = "sbelondrSW"
    end

	# get ssh key file to use scp
	config.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/tmp/ssh/id_rsa"
	config.vm.provision "file", source: "./scripts/scriptSW.sh", destination: "/tmp/scriptSW.sh"

    # install and config k3s
    control.vm.provision "shell", inline: <<-SHELL
	  bash /tmp/scriptSW.sh
    SHELL
  end

end
